// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818204549_PasswordNameChange")]
    partial class PasswordNameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2001, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hazar@example.com",
                            IsAdmin = true,
                            PasswordHashed = "hashed_password_1",
                            Username = "HazarN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2001, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            IsAdmin = false,
                            PasswordHashed = "hashed_password_2",
                            Username = "JohnD"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2001, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            IsAdmin = false,
                            PasswordHashed = "hashed_password_3",
                            Username = "JaneD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
